### ISSUE TITLE
TypeError: syncher.setDownloadDir is not a function

### ISSUE THREAD

**Issue by ofarukcaki** [mahhov/dwytpl#2]
When I run the example code on Readme I get this error

```C:\Users\Administrator\Desktop\be\index.js:9
syncher.setDownloadDir(path);
        ^

TypeError: syncher.setDownloadDir is not a function
    at Object.<anonymous> (C:\Users\Administrator\Desktop\be\index.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:74:12)
    at internal/main/run_main_module.js:18:47

````

**Comment by mahhov** [comment]
Thanks for finding this. An earlier [commit](https://github.com/mahhov/dwytpl/commit/5eddc8c6d0f03ad67bb46e287003ec6dbaffb7e5) removed this method and I didn't update the readme. The examples have been corrected now.
